services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9001:9000"
    environment:
      CLICKHOUSE_DB: security
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: clickhouse123
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
  clickhouse_logs:
